<%
  if ENV['BEAKER_HYPERVISOR']
    hypervisor = ENV['BEAKER_HYPERVISOR']
  else
    hypervisor = 'vagrant'
  end
-%>
# This nodeset spins up a simple one-host test VM for both EL6 and EL7
HOSTS:
  el7:
    roles:
      - server
      - default
      - master
    platform:   el-7-x86_64
    box:        centos/7
    hypervisor: <%= hypervisor %>

  el6:
    roles:
      - agent
      - client
    platform:   el-6-x86_64
    box:        centos/6
    hypervisor: <%= hypervisor %>

  el8:
    roles:
      - agent
      - client
    platform:   el-8-x86_64
    box:        centos/8
    hypervisor: <%= hypervisor %>

CONFIG:
  log_level: verbose
  type:      aio
  vagrant_memsize: 256
  ssh:
    keepalive: true
    keepalive_interval: 1
  ## vb_gui: true
<% if ENV['BEAKER_PUPPET_COLLECTION'] -%>
  puppet_collection: <%= ENV['BEAKER_PUPPET_COLLECTION'] %>
<% end -%>
